version: '3.3'

volumes:
  local_postgres_data:

networks:
  proxynet:
    driver: bridge

services:
  django:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    entrypoint: /entrypoint
    volumes:
      - ./app:/app
      - ./media:/project_manager/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=debug
      - POSTGRES_PASSWORD=debug
    command: /start
    restart: on-failure
    networks:
      - proxynet

  db:
    image: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=debug
      - POSTGRES_PASSWORD=debug
    ports:
      - "5432:5432"
    networks:
      - proxynet
