# Generated by Django 3.2.7 on 2024-08-19 06:21

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240819_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
