# Generated by Django 3.2.7 on 2024-08-19 13:45

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
    ]
